services:
  - type: web
    name: career-advisor-backend
    env: python
    buildCommand: |
      python --version
      pip install --upgrade pip
      pip install -r backend/requirements.txt
    startCommand: cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
      - key: DATABASE_URL
        fromDatabase:
          name: career-advisor-db
          property: connectionString
    plan: free
  
  - type: pserv
    name: career-advisor-db
    env: postgres
    plan: free
